#!/bin/bash
java -jar /home/corretor/corretor-automatico.jar \
    "/home/compilador/target/debug/t5" \
    gcc \
    /home/corretor/output \
    /home/corretor/casos-de-teste \
    "800268, 819498, 805757" \
    "t2 t3 t4 t5"